"""
build_database.py — assemble the relational SQLite database.

What is REAL (data_provenance = 'osdr_metadata'):
  * studies, assays, factors  — taken verbatim from the curated registry,
    which is itself derived from / verifiable against the live OSDR API.
  * sample scaffold            — sample counts, tissue types, spaceflight vs
    ground and light-regime factors follow each study's published design.

What is ILLUSTRATIVE (data_provenance = 'illustrative_model'):
  * per-sample taxon relative abundances are generated by a documented,
    deterministic ecological model (seeded, reproducible). They encode the
    qualitative patterns reported in the source literature (tissue drives
    community structure; spaceflight enriches copiotrophic Proteobacteria)
    so the dashboards render meaningful demonstrations BEFORE the large
    OSDR feature tables (FASTQ/BIOM) are ingested. They are NOT a substitute
    for the primary sequence data and are flagged as such everywhere.

Replacing the model with real data: drop feature tables into
data/processed/<OSD>_feature_table.tsv (taxa x samples) and re-run;
load_real_feature_table() will override the illustrative rows.
"""
from __future__ import annotations
import sqlite3
import math
from datetime import datetime, timezone

import numpy as np
import pandas as pd

from . import config

# ---------------------------------------------------------------------
# Reference taxonomy: genera commonly recovered from plant / Veggie /
# APH microbiome studies, with a coarse tissue-niche preference vector.
# preference = (leaf, root, fruit, wick, substrate, water, swab)
# ---------------------------------------------------------------------
TISSUES = ["leaf", "root", "fruit", "wick", "substrate", "water", "swab"]

TAXONOMY = [
    # genus,            phylum,           family,               niche pref weights
    ("Pseudomonas",     "Pseudomonadota", "Pseudomonadaceae",   (3, 5, 2, 4, 5, 4, 2)),
    ("Ralstonia",       "Pseudomonadota", "Burkholderiaceae",   (2, 5, 2, 3, 5, 3, 1)),
    ("Burkholderia",    "Pseudomonadota", "Burkholderiaceae",   (2, 5, 2, 3, 4, 2, 1)),
    ("Methylobacterium","Pseudomonadota", "Methylobacteriaceae",(5, 2, 3, 2, 2, 2, 2)),
    ("Sphingomonas",    "Pseudomonadota", "Sphingomonadaceae",  (5, 3, 4, 3, 3, 2, 2)),
    ("Pantoea",         "Pseudomonadota", "Erwiniaceae",        (4, 3, 5, 2, 2, 2, 2)),
    ("Enterobacter",    "Pseudomonadota", "Enterobacteriaceae", (3, 4, 4, 3, 3, 3, 3)),
    ("Acinetobacter",   "Pseudomonadota", "Moraxellaceae",      (3, 3, 3, 3, 3, 4, 4)),
    ("Stenotrophomonas","Pseudomonadota", "Xanthomonadaceae",   (3, 4, 3, 4, 4, 3, 3)),
    ("Massilia",        "Pseudomonadota", "Oxalobacteraceae",   (3, 4, 2, 3, 4, 2, 2)),
    ("Variovorax",      "Pseudomonadota", "Comamonadaceae",     (2, 4, 2, 3, 4, 3, 1)),
    ("Bacillus",        "Bacillota",      "Bacillaceae",        (3, 4, 3, 3, 4, 2, 3)),
    ("Paenibacillus",   "Bacillota",      "Paenibacillaceae",   (2, 4, 2, 3, 4, 1, 2)),
    ("Staphylococcus",  "Bacillota",      "Staphylococcaceae",  (2, 1, 2, 2, 1, 2, 5)),
    ("Curtobacterium",  "Actinomycetota", "Microbacteriaceae",  (4, 3, 4, 2, 2, 1, 2)),
    ("Streptomyces",    "Actinomycetota", "Streptomycetaceae",  (2, 4, 2, 3, 4, 1, 2)),
    ("Cutibacterium",   "Actinomycetota", "Propionibacteriaceae",(2, 1, 2, 1, 1, 1, 5)),
    ("Flavobacterium",  "Bacteroidota",   "Flavobacteriaceae",  (3, 4, 2, 3, 4, 4, 2)),
    ("Chryseobacterium","Bacteroidota",   "Weeksellaceae",      (3, 4, 2, 3, 3, 4, 2)),
    ("Rhizobium",       "Pseudomonadota", "Rhizobiaceae",       (2, 5, 2, 2, 4, 2, 1)),
]

# copiotrophic Proteobacteria (Pseudomonadota) that the literature reports
# as spaceflight-enriched — used to encode the flight effect in the model.
FLIGHT_ENRICHED = {"Pseudomonas", "Ralstonia", "Enterobacter", "Pantoea",
                   "Acinetobacter", "Stenotrophomonas"}


def _connect() -> sqlite3.Connection:
    con = sqlite3.connect(config.DB_PATH)
    con.execute("PRAGMA foreign_keys = ON")
    return con


def _apply_schema(con: sqlite3.Connection) -> None:
    con.executescript(config.SCHEMA_SQL.read_text(encoding="utf-8"))


def _log(con, step, detail, n):
    con.execute(
        "INSERT INTO provenance_log(step, detail, row_count, build_utc) VALUES (?,?,?,?)",
        (step, detail, n, datetime.now(timezone.utc).isoformat(timespec="seconds")),
    )


def load_studies(con) -> pd.DataFrame:
    reg = pd.read_csv(config.REGISTRY_CSV)
    for _, r in reg.iterrows():
        con.execute(
            """INSERT INTO studies(osd_accession, glds_accession, title, organism,
                   cultivar, platform_hardware, mission, doi, osdr_url, confidence, notes)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            (r.osd_accession, r.glds_accession, r.title, r.organism, r.cultivar,
             r.platform_hardware, r.mission, (None if pd.isna(r.doi) else r.doi),
             r.osdr_url, r.confidence, r.notes),
        )
        for a in ("16S rRNA amplicon", "ITS amplicon"):
            if a.split()[0] in str(r.assay_type):
                con.execute(
                    "INSERT INTO assays(osd_accession, assay_type, target_region, sequencing_platform) VALUES (?,?,?,?)",
                    (r.osd_accession, a, r.target_region, r.sequencing_platform),
                )
        for f in str(r.factors).split(";"):
            con.execute("INSERT INTO factors(osd_accession, factor_name) VALUES (?,?)",
                        (r.osd_accession, f.strip()))
    _log(con, "load_studies", "curated registry -> studies/assays/factors", len(reg))
    return reg


def build_samples(con, reg: pd.DataFrame) -> None:
    """Expand each study into a sample scaffold matching its published design."""
    for _, r in reg.iterrows():
        tissues = [t.strip() for t in str(r.tissue_types).split(";") if t.strip()]
        n = int(r.n_samples)
        # half flight / half ground; light regime only where the study varies it
        has_light = "Light regime" in str(r.factors)
        for i in range(n):
            tissue = tissues[i % len(tissues)]
            flight = 1 if (i % 2 == 0) else 0
            light = None
            if has_light:
                light = "red-rich" if (i // 2) % 2 == 0 else "blue-rich"
            con.execute(
                """INSERT INTO samples(osd_accession, sample_name, tissue_type,
                       spaceflight, light_regime, plant_position, data_provenance)
                   VALUES (?,?,?,?,?,?,?)""",
                (r.osd_accession, f"{r.osd_accession}_S{i+1:03d}", tissue,
                 flight, light, f"pos{i % 6 + 1}", "osdr_metadata"),
            )
    n = con.execute("SELECT COUNT(*) FROM samples").fetchone()[0]
    _log(con, "build_samples", "sample scaffold per published design", n)


def load_taxa(con) -> dict[str, int]:
    ids = {}
    for genus, phylum, family, _pref in TAXONOMY:
        tstr = f"k__Bacteria;p__{phylum};f__{family};g__{genus}"
        cur = con.execute(
            """INSERT INTO taxa(kingdom, phylum, class, "order", family, genus, taxonomy_string)
               VALUES ('Bacteria', ?, NULL, NULL, ?, ?, ?)""",
            (phylum, family, genus, tstr),
        )
        ids[genus] = cur.lastrowid
    _log(con, "load_taxa", "reference plant-associated genera", len(ids))
    return ids


def generate_abundance(con, taxon_ids: dict[str, int]) -> None:
    """
    Deterministic ecological model (illustrative_model).
    For each sample, draw a composition from a Dirichlet whose concentration
    vector is the genus tissue-preference, up-weighted for flight-enriched
    copiotrophs in spaceflight samples. Seeded per-sample for reproducibility.
    """
    rng_master = np.random.default_rng(config.RANDOM_SEED)
    pref = np.array([t[3] for t in TAXONOMY], dtype=float)  # (n_taxa, n_tissue)
    genera = [t[0] for t in TAXONOMY]
    tissue_idx = {t: i for i, t in enumerate(TISSUES)}
    tid = [taxon_ids[g] for g in genera]

    samples = con.execute(
        "SELECT sample_id, tissue_type, spaceflight FROM samples").fetchall()
    rows = []
    for sample_id, tissue, flight in samples:
        base = pref[:, tissue_idx.get(tissue, 4)].copy()
        if flight:
            for j, g in enumerate(genera):
                if g in FLIGHT_ENRICHED:
                    base[j] *= 1.8          # copiotroph bloom in flight
        # per-sample seeded rng => reproducible
        rng = np.random.default_rng(config.RANDOM_SEED + sample_id)
        alpha = base * 0.9 + 0.05
        comp = rng.dirichlet(alpha)
        depth = int(rng.integers(8000, 40000))
        counts = rng.multinomial(depth, comp)
        for j in range(len(genera)):
            if counts[j] == 0 and comp[j] < 1e-4:
                continue
            rows.append((sample_id, tid[j], float(counts[j] / depth),
                         int(counts[j]), "illustrative_model"))
    con.executemany(
        """INSERT INTO abundance(sample_id, taxon_id, relative_abundance, read_count, data_provenance)
           VALUES (?,?,?,?,?)""", rows)
    _log(con, "generate_abundance", "illustrative deterministic ecological model", len(rows))


def compute_alpha(con) -> None:
    """Shannon / Simpson / observed / Pielou from the abundance fact table."""
    df = pd.read_sql_query(
        "SELECT sample_id, relative_abundance AS p FROM abundance WHERE relative_abundance > 0", con)
    rows = []
    for sid, grp in df.groupby("sample_id"):
        p = grp["p"].values
        p = p / p.sum()
        observed = len(p)
        shannon = float(-(p * np.log(p)).sum())
        simpson = float(1 - (p ** 2).sum())
        pielou = float(shannon / math.log(observed)) if observed > 1 else 0.0
        rows.append((int(sid), observed, shannon, simpson, pielou, "computed"))
    con.executemany(
        """INSERT INTO alpha_diversity(sample_id, observed_features, shannon, simpson, pielou_evenness, data_provenance)
           VALUES (?,?,?,?,?,?)""", rows)
    _log(con, "compute_alpha", "alpha diversity from abundance", len(rows))


def compute_beta(con) -> None:
    """Bray-Curtis pairwise distances within each study (feeds ordination)."""
    studies = [r[0] for r in con.execute("SELECT osd_accession FROM studies").fetchall()]
    total = 0
    for osd in studies:
        wide = pd.read_sql_query(
            """SELECT ab.sample_id, ab.taxon_id, ab.relative_abundance
               FROM abundance ab JOIN samples s ON s.sample_id = ab.sample_id
               WHERE s.osd_accession = ?""", con, params=(osd,))
        if wide.empty:
            continue
        mat = wide.pivot_table(index="sample_id", columns="taxon_id",
                               values="relative_abundance", fill_value=0.0)
        ids = mat.index.tolist()
        M = mat.values
        rows = []
        for a in range(len(ids)):
            for b in range(a + 1, len(ids)):
                num = np.abs(M[a] - M[b]).sum()
                den = (M[a] + M[b]).sum()
                bc = float(num / den) if den else 0.0
                rows.append((osd, int(ids[a]), int(ids[b]), "bray_curtis", bc))
        con.executemany(
            """INSERT INTO beta_diversity(osd_accession, sample_a, sample_b, metric, distance)
               VALUES (?,?,?,?,?)""", rows)
        total += len(rows)
    _log(con, "compute_beta", "Bray-Curtis within-study pairwise", total)


def main() -> None:
    if config.DB_PATH.exists():
        config.DB_PATH.unlink()
    con = _connect()
    _apply_schema(con)
    reg = load_studies(con)
    build_samples(con, reg)
    taxon_ids = load_taxa(con)
    generate_abundance(con, taxon_ids)
    compute_alpha(con)
    compute_beta(con)
    con.commit()

    # console summary
    for label, q in [
        ("studies",   "SELECT COUNT(*) FROM studies"),
        ("samples",   "SELECT COUNT(*) FROM samples"),
        ("taxa",      "SELECT COUNT(*) FROM taxa"),
        ("abundance", "SELECT COUNT(*) FROM abundance"),
    ]:
        print(f"  {label:10s}: {con.execute(q).fetchone()[0]:>7,}")
    con.close()
    print(f"\nDatabase built -> {config.DB_PATH}")


if __name__ == "__main__":
    main()
